// Script para borrar todos los juegos y reseñas usando el backend (API REST)
// y luego crear 50 juegos nuevos con imágenes de Steam

const fetch = require("node-fetch");

const API_URL = process.env.API_URL || "http://localhost:3000/api";

// Lista de géneros válidos según el modelo
const generosValidos = [
  "Acción",
  "Aventura",
  "Rol",
  // ...
  "Simulación",
  "Deportes",
  "Carreras",
  "Plataformas",
  "Puzzle",
  "Metroidvania",
  "Indie",
  "Peleas",
];
// ...existing code...
const juegosBase = [
  {
    nombre: "BioShock Infinite",
  // ...
    genero: "Acción",
    plataforma: "PC, PS3, Xbox 360",
    imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/8870/capsule_231x87.jpg",
    sinopsis: "Una aventura en la ciudad flotante de Columbia.",
    desarrollador: "Irrational Games",
    tienda: "Steam",
    completado: true,
// ...existing code...
  },
  {
    nombre: "The Elder Scrolls V: Skyrim",
    año: 2011,
    genero: "Rol",
    plataforma: "PC, PS4, Xbox One, Switch",
    imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/72850/capsule_231x87.jpg",
    sinopsis: "Explora el vasto mundo de Skyrim.",
    desarrollador: "Bethesda",
    tienda: "Steam",
    completado: false,
    horasJugadas: 150,
  },
  {
    nombre: "Grand Theft Auto V",
    año: 2015,
    genero: "Acción",
    plataforma: "PC, PS4, Xbox One",
    imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/271590/capsule_231x87.jpg",
    sinopsis: "Vive el crimen en Los Santos.",
    desarrollador: "Rockstar North",
    tienda: "Steam",
    completado: false,
    horasJugadas: 120,
  },
  {
    nombre: "Left 4 Dead 2",
    año: 2009,
    genero: "Acción",
    plataforma: "PC, Xbox 360",
    imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/550/capsule_231x87.jpg",
    sinopsis: "Sobrevive a hordas de zombis con amigos.",
    desarrollador: "Valve",
    tienda: "Steam",
    completado: true,
    horasJugadas: 60,
  },
  {
    nombre: "PAYDAY 2",
    año: 2013,
    genero: "Acción",
    plataforma: "PC, PS4, Xbox One",
    imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/218620/capsule_231x87.jpg",
    sinopsis: "Planifica y ejecuta atracos cooperativos.",
    desarrollador: "OVERKILL",
    tienda: "Steam",
    completado: false,
    horasJugadas: 90,
  },
  {
    nombre: "The Forest",
    año: 2018,
    genero: "Indie",
    plataforma: "PC, PS4",
    imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/242760/capsule_231x87.jpg",
    sinopsis: "Sobrevive en un bosque lleno de misterios.",
    desarrollador: "Endnight Games",
    tienda: "Steam",
    completado: false,
    horasJugadas: 40,
  },
  {
    nombre: "Phasmophobia",
    año: 2020,
    genero: "Indie",
    plataforma: "PC",
    imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/739630/capsule_231x87.jpg",
    sinopsis: "Investiga casas embrujadas con amigos.",
    desarrollador: "Kinetic Games",
    tienda: "Steam",
    completado: false,
    horasJugadas: 30,
  },
  {
    nombre: "No Man's Sky",
    año: 2016,
    genero: "Aventura",
    plataforma: "PC, PS4, Xbox One",
    imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/275850/capsule_231x87.jpg",
    sinopsis: "Explora un universo infinito.",
    desarrollador: "Hello Games",
    tienda: "Steam",
    completado: false,
    horasJugadas: 100,
  },
  {
    nombre: "Don't Starve",
    año: 2013,
    genero: "Aventura",
    plataforma: "PC, Switch, PS4, Xbox One",
    imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/219740/capsule_231x87.jpg",
    sinopsis: "Sobrevive en un mundo oscuro y extraño.",
    desarrollador: "Klei Entertainment",
    tienda: "Steam",
    completado: false,
    horasJugadas: 70,
  },
  {
    nombre: "Portal",
    año: 2007,
    genero: "Puzzle",
    plataforma: "PC, Xbox 360, PS3",
    imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/400/capsule_231x87.jpg",
    sinopsis: "El clásico de puzzles con portales.",
    desarrollador: "Valve",
    tienda: "Steam",
    completado: true,
    horasJugadas: 10,
  },
  // ...agrega aquí los otros juegos hasta llegar a 50...
  {
    nombre: "Half-Life 2",
    año: 2004,
    genero: "Acción",
    plataforma: "PC, Xbox, Xbox 360",
    imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/220/capsule_231x87.jpg",
    sinopsis: "La revolución de los shooters en primera persona.",
    desarrollador: "Valve",
    tienda: "Steam",
    completado: true,
    horasJugadas: 25,
  },
  {
    nombre: "ARK: Survival Evolved",
    año: 2017,
    genero: "Aventura",
    plataforma: "PC, PS4, Xbox One, Switch",
    imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/346110/capsule_231x87.jpg",
    sinopsis: "Sobrevive entre dinosaurios y construye tu base.",
    desarrollador: "Studio Wildcard",
    tienda: "Steam",
    completado: false,
    horasJugadas: 80,
  },
  {
    nombre: "Euro Truck Simulator 2",
    año: 2012,
    genero: "Simulación",
    plataforma: "PC",
    imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/227300/capsule_231x87.jpg",
    sinopsis: "Conduce camiones por toda Europa.",
    desarrollador: "SCS Software",
    tienda: "Steam",
    completado: false,
    horasJugadas: 90,
  },
  {
    nombre: "The Sims 4",
    año: 2014,
    genero: "Simulación",
    plataforma: "PC, PS4, Xbox One",
    imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/1222670/capsule_231x87.jpg",
    sinopsis: "Crea y controla personas en un mundo virtual.",
    desarrollador: "Maxis",
    tienda: "Steam",
    completado: false,
    horasJugadas: 120,
  },
  {
    nombre: "Monster Hunter: World",
    año: 2018,
    genero: "Acción",
    plataforma: "PC, PS4, Xbox One",
    imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/582010/capsule_231x87.jpg",
    sinopsis: "Caza monstruos gigantes en un mundo vibrante.",
    desarrollador: "Capcom",
    tienda: "Steam",
    completado: false,
    horasJugadas: 110,
  },
  {
    nombre: "Sekiro: Shadows Die Twice",
    año: 2019,
    genero: "Acción",
    plataforma: "PC, PS4, Xbox One",
    imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/814380/capsule_231x87.jpg",
    sinopsis: "Acción y sigilo en el Japón feudal.",
    desarrollador: "FromSoftware",
    tienda: "Steam",
    completado: true,
    horasJugadas: 50,
  },
  {
    nombre: "HITMAN 2",
    año: 2018,
    genero: "Estrategia",
    plataforma: "PC, PS4, Xbox One",
    imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/863550/capsule_231x87.jpg",
    sinopsis: "El asesino silencioso regresa con nuevos contratos.",
    desarrollador: "IO Interactive",
    tienda: "Steam",
    completado: false,
    horasJugadas: 40,
  },
  {
    nombre: "DARK SOULS: REMASTERED",
    año: 2018,
    genero: "Acción",
    plataforma: "PC, PS4, Xbox One, Switch",
    imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/570940/capsule_231x87.jpg",
    sinopsis: "El clásico desafiante regresa remasterizado.",
    desarrollador: "FromSoftware",
    tienda: "Steam",
    completado: true,
    horasJugadas: 80,
  },
  {
    nombre: "Mortal Kombat 11",
    año: 2019,
    genero: "Acción",
    plataforma: "PC, PS4, Xbox One, Switch",
    imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/976310/capsule_231x87.jpg",
    sinopsis: "El torneo de lucha más brutal.",
    desarrollador: "NetherRealm Studios",
    tienda: "Steam",
    completado: false,
    horasJugadas: 30,
  },
  {
    nombre: "The Long Dark",
    año: 2017,
    genero: "Aventura",
    plataforma: "PC, PS4, Xbox One, Switch",
    imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/305620/capsule_231x87.jpg",
    sinopsis: "Sobrevive en el frío extremo del norte.",
    desarrollador: "Hinterland Studio",
    tienda: "Steam",
    completado: false,
    horasJugadas: 60,
  },
  // ...continúa agregando juegos únicos hasta llegar a 50...
  {
    nombre: "Horizon Zero Dawn",
    año: 2020,
    genero: "Aventura",
    plataforma: "PC, PS4",
    imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/1151640/capsule_231x87.jpg",
    sinopsis: "Explora un mundo postapocalíptico con máquinas.",
    desarrollador: "Guerrilla Games",
    tienda: "Steam",
    completado: false,
    horasJugadas: 90,
  },
  {
    nombre: "Cyberpunk 2077",
    año: 2020,
  genero: "Rol",
    plataforma: "PC, PS4, Xbox One",
    imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/1091500/capsule_231x87.jpg",
    sinopsis: "Vive en Night City, una megalópolis obsesionada con el poder.",
    desarrollador: "CD Projekt Red",
    tienda: "Steam",
    completado: false,
    horasJugadas: 100,
  },
  {
    nombre: "Dying Light",
    año: 2015,
    genero: "Indie",
    plataforma: "PC, PS4, Xbox One",
    imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/239140/capsule_231x87.jpg",
    sinopsis: "Sobrevive a los zombis en un mundo abierto.",
    desarrollador: "Techland",
    tienda: "Steam",
    completado: false,
    horasJugadas: 70,
  },
  {
    nombre: "The Talos Principle",
    año: 2014,
    genero: "Puzzle",
    plataforma: "PC, PS4, Xbox One",
    imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/257510/capsule_231x87.jpg",
    sinopsis: "Un desafiante juego de puzzles filosófico.",
    desarrollador: "Croteam",
    tienda: "Steam",
    completado: false,
    horasJugadas: 40,
  },
  {
    nombre: "INSIDE",
    año: 2016,
    genero: "Plataformas",
    plataforma: "PC, PS4, Xbox One, Switch",
    imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/304430/capsule_231x87.jpg",
    sinopsis: "Un oscuro y atmosférico juego de plataformas.",
    desarrollador: "Playdead",
    tienda: "Steam",
    completado: true,
    horasJugadas: 15,
  },
  {
    nombre: "Little Nightmares",
    año: 2017,
  genero: "Indie",
    plataforma: "PC, PS4, Xbox One, Switch",
    imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/424840/capsule_231x87.jpg",
    sinopsis: "Escapa de un mundo de pesadilla.",
    desarrollador: "Tarsier Studios",
    tienda: "Steam",
    completado: true,
    horasJugadas: 20,
  },
  {
    nombre: "HUMANKIND",
    año: 2021,
    genero: "Estrategia",
    plataforma: "PC",
    imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/1124300/capsule_231x87.jpg",
    sinopsis: "Crea tu propia civilización y cambia la historia.",
    desarrollador: "AMPLITUDE Studios",
    tienda: "Steam",
    completado: false,
    horasJugadas: 30,
  },
  {
    nombre: "GRID Legends",
    año: 2022,
    genero: "Carreras",
    plataforma: "PC, PS4, Xbox One",
    imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/1399730/capsule_231x87.jpg",
    sinopsis: "Carreras intensas y emocionantes.",
    desarrollador: "Codemasters",
    tienda: "Steam",
    completado: false,
    horasJugadas: 25,
  },
  {
    nombre: "Frostpunk",
    año: 2018,
    genero: "Estrategia",
    plataforma: "PC, PS4, Xbox One",
    imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/323190/capsule_231x87.jpg",
    sinopsis: "Gestiona la última ciudad en la Tierra helada.",
    desarrollador: "11 bit studios",
    tienda: "Steam",
    completado: false,
    horasJugadas: 50,
  },
  {
    nombre: "RimWorld",
    año: 2018,
    genero: "Simulación",
    plataforma: "PC",
    imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/294100/capsule_231x87.jpg",
    sinopsis: "Gestiona una colonia en un planeta remoto.",
    desarrollador: "Ludeon Studios",
    tienda: "Steam",
    completado: false,
    horasJugadas: 200,
  },
  {
    nombre: "Spelunky 2",
    año: 2020,
    genero: "Plataformas",
    plataforma: "PC, PS4, Switch",
    imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/418530/capsule_231x87.jpg",
    sinopsis: "Explora cuevas llenas de peligros y tesoros.",
    desarrollador: "Mossmouth",
    tienda: "Steam",
    completado: false,
    horasJugadas: 60,
  },
  // ...continúa hasta 50 juegos únicos...
  {
    nombre: "The Stanley Parable",
    año: 2013,
    genero: "Puzzle",
    plataforma: "PC",
    imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/221910/capsule_231x87.jpg",
    sinopsis: "Una aventura narrativa única y sorprendente.",
    desarrollador: "Galactic Cafe",
    tienda: "Steam",
    completado: true,
    horasJugadas: 10,
  },
  {
    nombre: "Super Meat Boy",
    año: 2010,
    genero: "Plataformas",
    plataforma: "PC, Switch, PS4, Xbox One",
    imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/40800/capsule_231x87.jpg",
    sinopsis: "Un plataformas rápido y desafiante.",
    desarrollador: "Team Meat",
    tienda: "Steam",
    completado: false,
    horasJugadas: 30,
  },
  {
    nombre: "Baba Is You",
    año: 2019,
    genero: "Puzzle",
    plataforma: "PC, Switch",
    imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/736260/capsule_231x87.jpg",
    sinopsis: "Resuelve puzzles cambiando las reglas.",
    desarrollador: "Hempuli Oy",
    tienda: "Steam",
    completado: false,
    horasJugadas: 25,
  },
  {
    nombre: "Hunt: Showdown",
    año: 2019,
    genero: "Acción",
    plataforma: "PC, PS4, Xbox One",
    imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/594650/capsule_231x87.jpg",
    sinopsis: "Caza monstruos y compite contra otros jugadores.",
    desarrollador: "Crytek",
    tienda: "Steam",
    completado: false,
    horasJugadas: 40,
  },
  {
    nombre: "It Takes Two",
    año: 2021,
    genero: "Aventura",
    plataforma: "PC, PS4, Xbox One, Switch",
    imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/1426210/capsule_231x87.jpg",
    sinopsis: "Una aventura cooperativa para dos jugadores.",
    desarrollador: "Hazelight Studios",
    tienda: "Steam",
    completado: true,
    horasJugadas: 20,
  },
  {
    nombre: "Valheim",
    año: 2021,
    genero: "Aventura",
    plataforma: "PC",
    imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/892970/capsule_231x87.jpg",
    sinopsis: "Sobrevive y explora en un mundo vikingo procedimental.",
    desarrollador: "Iron Gate AB",
    tienda: "Steam",
    completado: false,
    horasJugadas: 80,
  },
  {
    nombre: "Risk of Rain 2",
    año: 2020,
    genero: "Acción",
    plataforma: "PC, Switch, PS4, Xbox One",
    imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/632360/capsule_231x87.jpg",
    sinopsis: "Acción roguelike en tercera persona.",
    desarrollador: "Hopoo Games",
    tienda: "Steam",
    completado: false,
    horasJugadas: 60,
  },
  {
    nombre: "Totally Accurate Battle Simulator",
    año: 2021,
    genero: "Estrategia",
    plataforma: "PC, Xbox One",
    imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/508440/capsule_231x87.jpg",
    sinopsis: "Simula batallas absurdas y divertidas.",
    desarrollador: "Landfall",
    tienda: "Steam",
    completado: false,
    horasJugadas: 30,
  },
  {
    nombre: "Slime Rancher",
    año: 2017,
    genero: "Simulación",
    plataforma: "PC, Xbox One, PS4",
    imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/433340/capsule_231x87.jpg",
    sinopsis: "Cría y recolecta slimes en un mundo colorido.",
    desarrollador: "Monomi Park",
    tienda: "Steam",
    completado: false,
    horasJugadas: 50,
  },
  {
    nombre: "Enter the Gungeon",
    año: 2016,
    genero: "Acción",
    plataforma: "PC, Switch, PS4, Xbox One",
    imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/311690/capsule_231x87.jpg",
    sinopsis: "Dispara y esquiva balas en este roguelike.",
    desarrollador: "Dodge Roll",
    tienda: "Steam",
    completado: false,
    horasJugadas: 70,
  },
  {
    nombre: "Oxygen Not Included",
    año: 2019,
    genero: "Simulación",
    plataforma: "PC",
    imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/457140/capsule_231x87.jpg",
    sinopsis: "Gestiona una colonia espacial subterránea.",
    desarrollador: "Klei Entertainment",
    tienda: "Steam",
    completado: false,
    horasJugadas: 120,
  },
  {
    nombre: "The Escapists 2",
    año: 2017,
    genero: "Estrategia",
    plataforma: "PC, Switch, PS4, Xbox One",
    imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/641990/capsule_231x87.jpg",
    sinopsis: "Planea y ejecuta fugas de prisión.",
    desarrollador: "Team17",
    tienda: "Steam",
    completado: false,
    horasJugadas: 40,
  },
  {
    nombre: "Cities: Skylines",
    año: 2015,
    genero: "Simulación",
    plataforma: "PC, PS4, Xbox One, Switch",
    imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/255710/capsule_231x87.jpg",
    sinopsis: "Construye y gestiona tu propia ciudad.",
    desarrollador: "Colossal Order",
    tienda: "Steam",
    completado: false,
    horasJugadas: 150,
  },
  {
    nombre: "The Messenger",
    año: 2018,
    genero: "Plataformas",
    plataforma: "PC, Switch, PS4, Xbox One",
    imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/764790/capsule_231x87.jpg",
    sinopsis: "Un plataformas de acción con viajes en el tiempo.",
    desarrollador: "Sabotage Studio",
    tienda: "Steam",
    completado: false,
    horasJugadas: 30,
  },
  {
    nombre: "Katana ZERO",
    año: 2019,
    genero: "Acción",
    plataforma: "PC, Switch, Xbox One",
    imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/460950/capsule_231x87.jpg",
    sinopsis: "Acción rápida y narrativa intrigante.",
    desarrollador: "Askiisoft",
    tienda: "Steam",
    completado: false,
    horasJugadas: 20,
  },
  {
    nombre: "Outer Wilds",
    año: 2020,
    genero: "Aventura",
    plataforma: "PC, PS4, Xbox One",
    imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/753640/capsule_231x87.jpg",
    sinopsis: "Explora un sistema solar en bucle temporal.",
    desarrollador: "Mobius Digital",
    tienda: "Steam",
    completado: true,
    horasJugadas: 25,
  },
  {
    nombre: "Spiritfarer",
    año: 2020,
    genero: "Aventura",
    plataforma: "PC, Switch, PS4, Xbox One",
    imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/972660/capsule_231x87.jpg",
    sinopsis: "Ayuda a los espíritus a encontrar la paz.",
    desarrollador: "Thunder Lotus Games",
    tienda: "Steam",
    completado: true,
    horasJugadas: 40,
  },
  {
    nombre: "Disco Elysium",
    año: 2019,
    genero: "Rol",
    plataforma: "PC, PS4, Xbox One, Switch",
    imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/632470/capsule_231x87.jpg",
    sinopsis: "Un RPG detectivesco con narrativa profunda.",
    desarrollador: "ZA/UM",
    tienda: "Steam",
    completado: false,
    horasJugadas: 60,
  },
  {
    nombre: "Loop Hero",
    año: 2021,
    genero: "Estrategia",
    plataforma: "PC, Switch",
    imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/1282730/capsule_231x87.jpg",
    sinopsis: "Un roguelike de cartas y gestión de bucles.",
    desarrollador: "Four Quarters",
    tienda: "Steam",
    completado: false,
    horasJugadas: 30,
  },
  {
    nombre: "A Short Hike",
    año: 2019,
    genero: "Aventura",
    plataforma: "PC, Switch",
    imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/1055540/capsule_231x87.jpg",
    sinopsis: "Explora una isla y haz nuevos amigos.",
    desarrollador: "adamgryu",
    tienda: "Steam",
    completado: true,
    horasJugadas: 10,
  },
  {
    nombre: "Vampire Survivors",
    año: 2022,
    genero: "Acción",
    plataforma: "PC, Xbox One, Switch",
    imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/1794680/capsule_231x87.jpg",
    sinopsis: "Sobrevive a hordas de enemigos en partidas rápidas.",
    desarrollador: "poncle",
    tienda: "Steam",
    completado: false,
    horasJugadas: 40,
  },
  {
    nombre: "Teardown",
    año: 2022,
    genero: "Acción",
    plataforma: "PC",
    imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/1167630/capsule_231x87.jpg",
    sinopsis:
      "Destruye y planifica robos en entornos totalmente destructibles.",
    desarrollador: "Tuxedo Labs",
    tienda: "Steam",
    completado: false,
    horasJugadas: 30,
  },
  {
    nombre: "Satisfactory",
    año: 2020,
    genero: "Simulación",
    plataforma: "PC",
    imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/526870/capsule_231x87.jpg",
    sinopsis: "Construye fábricas en un planeta alienígena.",
    desarrollador: "Coffee Stain Studios",
    tienda: "Steam",
    completado: false,
    horasJugadas: 100,
  },
  {
    nombre: "Tunic",
    año: 2022,
    genero: "Aventura",
    plataforma: "PC, Xbox One, Switch, PS4",
    imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/553420/capsule_231x87.jpg",
    sinopsis: "Explora un mundo misterioso como un pequeño zorro.",
    desarrollador: "Andrew Shouldice",
    tienda: "Steam",
    completado: false,
    horasJugadas: 20,
  },
  {
    nombre: "Death's Door",
    año: 2021,
    genero: "Acción",
    plataforma: "PC, Switch, PS4, Xbox One",
    imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/894020/capsule_231x87.jpg",
    sinopsis: "Acción y exploración en un mundo de fantasía oscura.",
    desarrollador: "Acid Nerve",
    tienda: "Steam",
    completado: false,
    horasJugadas: 30,
  },
  {
    nombre: "Unpacking",
    año: 2021,
    genero: "Puzzle",
    plataforma: "PC, Switch, Xbox One, PS4",
    imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/1135690/capsule_231x87.jpg",
    sinopsis: "Desempaqueta y organiza la vida de una persona.",
    desarrollador: "Witch Beam",
    tienda: "Steam",
    completado: true,
    horasJugadas: 10,
  },
  {
    nombre: "Return of the Obra Dinn",
    año: 2018,
    genero: "Puzzle",
    plataforma: "PC, Switch, PS4, Xbox One",
    imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/653530/capsule_231x87.jpg",
    sinopsis: "Investiga el destino de la tripulación de un barco misterioso.",
    desarrollador: "Lucas Pope",
    tienda: "Steam",
    completado: true,
    horasJugadas: 15,
  },
  {
    nombre: "Papers, Please",
    año: 2013,
    genero: "Puzzle",
    plataforma: "PC, Switch",
    imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/239030/capsule_231x87.jpg",
    sinopsis: "Controla la inmigración en un país ficticio.",
    desarrollador: "Lucas Pope",
    tienda: "Steam",
    completado: false,
    horasJugadas: 20,
  },
  {
    nombre: "Hotline Miami",
    año: 2012,
    genero: "Acción",
    plataforma: "PC, Switch, PS4, Xbox One",
    imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/219150/capsule_231x87.jpg",
    sinopsis: "Acción frenética y música synthwave.",
    desarrollador: "Dennaton Games",
    tienda: "Steam",
    completado: true,
    horasJugadas: 15,
  },
  {
    nombre: "Journey",
    año: 2020,
    genero: "Aventura",
    plataforma: "PC, PS4",
    imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/638230/capsule_231x87.jpg",
    sinopsis: "Una emotiva travesía por el desierto.",
    desarrollador: "thatgamecompany",
    tienda: "Steam",
    completado: true,
    horasJugadas: 5,
  },
  {
    nombre: "GRIS",
    año: 2018,
    genero: "Plataformas",
    plataforma: "PC, Switch, PS4, Xbox One",
    imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/683320/capsule_231x87.jpg",
    sinopsis: "Una experiencia visual y sonora única.",
    desarrollador: "Nomada Studio",
    tienda: "Steam",
    completado: true,
    horasJugadas: 10,
  },
  {
    nombre: "Celeste Classic",
    año: 2016,
    genero: "Plataformas",
    plataforma: "PC",
    imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/822250/capsule_231x87.jpg",
    sinopsis: "La versión original de Celeste, desafiante y adictiva.",
    desarrollador: "Matt Makes Games",
    tienda: "Steam",
    completado: true,
    horasJugadas: 5,
  },
  {
    nombre: "Superliminal",
    año: 2020,
    genero: "Puzzle",
    plataforma: "PC, Switch, PS4, Xbox One",
    imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/1049410/capsule_231x87.jpg",
    sinopsis: "Juega con la perspectiva en puzzles surrealistas.",
    desarrollador: "Pillow Castle",
    tienda: "Steam",
    completado: false,
    horasJugadas: 10,
  },
  {
    nombre: "My Friend Pedro",
    año: 2019,
    genero: "Acción",
    plataforma: "PC, Switch, PS4, Xbox One",
    imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/557340/capsule_231x87.jpg",
    sinopsis: "Acción acrobática y disparos en cámara lenta.",
    desarrollador: "DeadToast Entertainment",
    tienda: "Steam",
    completado: false,
    horasJugadas: 15,
  },
  {
    nombre: "Hyper Light Drifter",
    año: 2016,
    genero: "Acción",
    plataforma: "PC, Switch, PS4, Xbox One",
    imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/257850/capsule_231x87.jpg",
    sinopsis: "Acción y exploración en un mundo pixel art.",
    desarrollador: "Heart Machine",
    tienda: "Steam",
    completado: false,
    horasJugadas: 20,
  },
  {
    nombre: "The Witness",
    año: 2016,
    genero: "Puzzle",
    plataforma: "PC, PS4, Xbox One",
    imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/210970/capsule_231x87.jpg",
    sinopsis: "Explora una isla llena de puzzles.",
    desarrollador: "Thekla, Inc.",
    tienda: "Steam",
    completado: false,
    horasJugadas: 40,
  },
  {
    nombre: "Firewatch",
    año: 2016,
    genero: "Aventura",
    plataforma: "PC, PS4, Xbox One",
    imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/383870/capsule_231x87.jpg",
    sinopsis: "Vive una historia de misterio en un bosque.",
    desarrollador: "Campo Santo",
    tienda: "Steam",
    completado: true,
    horasJugadas: 10,
  },
  {
    nombre: "Bastion",
    año: 2011,
    genero: "Acción",
    plataforma: "PC, Switch, PS4, Xbox One",
    imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/107100/capsule_231x87.jpg",
    sinopsis: "Acción y narrativa en un mundo colorido.",
    desarrollador: "Supergiant Games",
    tienda: "Steam",
    completado: true,
    horasJugadas: 15,
  },
  {
    nombre: "Broforce",
    año: 2015,
    genero: "Acción",
    plataforma: "PC, Switch, PS4",
    imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/274190/capsule_231x87.jpg",
    sinopsis: "Acción explosiva y cooperativa.",
    desarrollador: "Free Lives",
    tienda: "Steam",
    completado: false,
    horasJugadas: 20,
  },
  {
    nombre: "FEZ",
    año: 2012,
    genero: "Puzzle",
    plataforma: "PC, Switch, PS4, Xbox One",
    imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/224760/capsule_231x87.jpg",
    sinopsis: "Un plataformas de puzzles en 2D y 3D.",
    desarrollador: "Polytron Corporation",
    tienda: "Steam",
    completado: false,
    horasJugadas: 20,
  },
  {
    nombre: "Terraria: Journey's End",
    año: 2020,
    genero: "Aventura",
    plataforma: "PC, Switch, PS4, Xbox One",
    imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/105600/capsule_231x87.jpg",
    sinopsis: "La actualización final de Terraria, con más contenido.",
    desarrollador: "Re-Logic",
    tienda: "Steam",
    completado: true,
    horasJugadas: 100,
  },
  {
    nombre: "Portal Stories: Mel",
    año: 2015,
    genero: "Puzzle",
    plataforma: "PC",
    imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/317400/capsule_231x87.jpg",
    sinopsis: "Una expansión gratuita de puzzles para Portal 2.",
    desarrollador: "Prism Studios",
    tienda: "Steam",
    completado: false,
    horasJugadas: 15,
  },
  {
    nombre: "The Room",
    año: 2014,
    genero: "Puzzle",
    plataforma: "PC, Switch, Móvil",
    imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/288160/capsule_231x87.jpg",
    sinopsis: "Resuelve intrincados puzzles en habitaciones misteriosas.",
    desarrollador: "Fireproof Games",
    tienda: "Steam",
    completado: false,
    horasJugadas: 10,
  },
  {
    nombre: "Oxenfree",
    año: 2016,
    genero: "Aventura",
    plataforma: "PC, Switch, PS4, Xbox One",
    imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/388880/capsule_231x87.jpg",
    sinopsis: "Una aventura sobrenatural con decisiones narrativas.",
    desarrollador: "Night School Studio",
    tienda: "Steam",
    completado: true,
    horasJugadas: 10,
  },
  {
    nombre: "Celeste Classic 2",
    año: 2021,
    genero: "Plataformas",
    plataforma: "PC",
    imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/1675290/capsule_231x87.jpg",
    sinopsis: "La secuela gratuita de Celeste Classic.",
    desarrollador: "Matt Makes Games",
    tienda: "Steam",
    completado: false,
    horasJugadas: 5,
  },
  {
    nombre: "Superhot",
    año: 2016,
    genero: "Acción",
    plataforma: "PC, Switch, PS4, Xbox One",
    imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/322500/capsule_231x87.jpg",
    sinopsis: "El tiempo solo avanza cuando te mueves.",
    desarrollador: "SUPERHOT Team",
    tienda: "Steam",
    completado: false,
    horasJugadas: 15,
  },
  {
    nombre: "The Banner Saga",
    año: 2014,
    genero: "Estrategia",
    plataforma: "PC, Switch, PS4, Xbox One",
    imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/237990/capsule_231x87.jpg",
    sinopsis: "Una épica saga vikinga de estrategia y narrativa.",
    desarrollador: "Stoic",
    tienda: "Steam",
    completado: false,
    horasJugadas: 30,
  },
  {
    nombre: "Wargroove",
    año: 2019,
    genero: "Estrategia",
    plataforma: "PC, Switch, PS4, Xbox One",
    imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/607050/capsule_231x87.jpg",
    sinopsis: "Estrategia táctica por turnos con estilo retro.",
    desarrollador: "Chucklefish",
    tienda: "Steam",
    completado: false,
    horasJugadas: 25,
  },
  {
    nombre: "A Hat in Time",
    año: 2017,
    genero: "Plataformas",
    plataforma: "PC, Switch, PS4, Xbox One",
    imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/253230/capsule_231x87.jpg",
    sinopsis: "Una adorable aventura de plataformas en 3D.",
    desarrollador: "Gears for Breakfast",
    tienda: "Steam",
    completado: true,
    horasJugadas: 20,
  },
  {
    nombre: "The Talos Principle 2",
    año: 2023,
    genero: "Puzzle",
    plataforma: "PC, PS5, Xbox Series X/S",
    imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/835960/capsule_231x87.jpg",
    sinopsis: "La secuela del aclamado juego de puzzles filosófico.",
    desarrollador: "Croteam",
    tienda: "Steam",
    completado: false,
    horasJugadas: 20,
  },
  {
    nombre: "Dredge",
    año: 2023,
    genero: "Aventura",
    plataforma: "PC, Switch, PS4, Xbox One",
    imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/1562430/capsule_231x87.jpg",
    sinopsis: "Pesca y explora misterios en aguas oscuras.",
    desarrollador: "Black Salt Games",
    tienda: "Steam",
    completado: false,
    horasJugadas: 15,
  },
  {
    nombre: "Pizza Tower",
    año: 2023,
    genero: "Plataformas",
    plataforma: "PC",
    imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/2231450/capsule_231x87.jpg",
    sinopsis: "Un plataformas rápido y caótico inspirado en los clásicos.",
    desarrollador: "Tour De Pizza",
    tienda: "Steam",
    completado: false,
    horasJugadas: 10,
  },
  {
    nombre: "Dave the Diver",
    año: 2023,
    genero: "Aventura",
    plataforma: "PC, Switch",
    imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/1868140/capsule_231x87.jpg",
    sinopsis: "Explora el océano y gestiona un restaurante de sushi.",
    desarrollador: "MINTROCKET",
    tienda: "Steam",
    completado: false,
    horasJugadas: 20,
  },
  {
    nombre: "Viewfinder",
    año: 2023,
    genero: "Puzzle",
    plataforma: "PC, PS5",
    imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/1382070/capsule_231x87.jpg",
    sinopsis: "Manipula la realidad con fotografías para resolver puzzles.",
    desarrollador: "Sad Owl Studios",
    tienda: "Steam",
    completado: false,
    horasJugadas: 10,
  },
  {
    nombre: "Cocoon",
    año: 2023,
    genero: "Puzzle",
    plataforma: "PC, Switch, PS4, Xbox One",
    imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/1497440/capsule_231x87.jpg",
    sinopsis: "Un juego de puzzles de los creadores de Limbo e Inside.",
    desarrollador: "Geometric Interactive",
    tienda: "Steam",
    completado: false,
    horasJugadas: 10,
  },
  {
    nombre: "Sea of Stars",
    año: 2023,
    genero: "Rol",
    plataforma: "PC, Switch, PS4, Xbox One",
    imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/1244090/capsule_231x87.jpg",
    sinopsis: "Un RPG retro inspirado en los clásicos.",
    desarrollador: "Sabotage Studio",
    tienda: "Steam",
    completado: false,
    horasJugadas: 40,
  },
  {
    nombre: "Blasphemous 2",
    año: 2023,
    genero: "Acción",
    plataforma: "PC, Switch, PS4, Xbox One",
    imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/2114740/capsule_231x87.jpg",
    sinopsis: "La secuela del aclamado metroidvania español.",
    desarrollador: "The Game Kitchen",
    tienda: "Steam",
    completado: false,
    horasJugadas: 30,
  },
  {
    nombre: "Lies of P",
    año: 2023,
    genero: "Acción",
    plataforma: "PC, PS4, PS5, Xbox One, Xbox Series X/S",
    imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/1627720/capsule_231x87.jpg",
    sinopsis: "Un soulslike inspirado en Pinocho.",
    desarrollador: "NEOWIZ",
    tienda: "Steam",
    completado: false,
    horasJugadas: 50,
  },
  {
    nombre: "Cocoon 2",
    año: 2025,
    genero: "Puzzle",
    plataforma: "PC, Switch, PS5",
    imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/1497440/capsule_231x87.jpg",
    sinopsis: "La secuela de Cocoon, con nuevos mundos y puzzles.",
    desarrollador: "Geometric Interactive",
    tienda: "Steam",
    completado: false,
    horasJugadas: 10,
  },
];

const juegosEjemplo = juegosBase.slice(0, 50).map((juego) => ({
  nombre: juego.nombre,
  año: juego.año,
  genero: juego.genero,
  plataforma: juego.plataforma,
  imagen: juego.imagen,
  sinopsis: juego.sinopsis,
  desarrollador: juego.desarrollador,
  tienda: juego.tienda,
  completado: juego.completado,
  horasJugadas: juego.horasJugadas,
  // Puedes agregar favorito, pendiente, fechaCreacion si lo deseas
}));

async function borrarTodo() {
  // Borrar reseñas
  const resenias = await fetch(`${API_URL}/resenias`).then((r) => r.json());
  for (const r of resenias) {
    await fetch(`${API_URL}/resenias/${r.id || r._id}`, { method: "DELETE" });
  }
  // Borrar juegos
  const juegos = await fetch(`${API_URL}/juegos`).then((r) => r.json());
  for (const j of juegos) {
    await fetch(`${API_URL}/juegos/${j.id || j._id}`, { method: "DELETE" });
  }
}

async function crearJuegos() {
  for (const juego of juegosEjemplo) {
    // Asegurarse de enviar los campos correctos y tipos válidos
    const payload = {
      nombre: String(juego.nombre),
      año: parseInt(juego.año),
      genero: String(juego.genero),
      plataforma: String(juego.plataforma),
      imagen: String(juego.imagen),
      sinopsis: String(juego.sinopsis),
      desarrollador: String(juego.desarrollador),
      tienda: String(juego.tienda),
      completado: Boolean(juego.completado),
      horasJugadas: Number(juego.horasJugadas),
    };
    console.log("\nEnviando juego:", JSON.stringify(payload, null, 2));
    const res = await fetch(`${API_URL}/juegos`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(payload),
    });
    const respuestaTexto = await res.text();
    if (!res.ok) {
      console.error(`Error creando juego: ${payload.nombre}`);
      console.error("Respuesta del backend:", respuestaTexto);
    } else {
      console.log(`Juego creado: ${payload.nombre}`);
      console.log("Respuesta del backend:", respuestaTexto);
    }
  }
}

(async () => {
  console.log("Borrando todos los juegos y reseñas...");
  await borrarTodo();
  console.log("Creando 50 juegos de ejemplo...");
  await crearJuegos();
  console.log("¡Listo!");
})();
